#!/bin/sh /etc/rc.common

NAME=mesh
START=89
STOP=11

# Include Mesh work-file
. /usr/share/pb-mesh/mesh.common

#Load config
. /etc/mesh.config

start() {
  build_mesh
}

stop() {
  destroy_mesh
}


