#!/bin/sh /etc/rc.common

NAME=mesh
START=89
STOP=11
EXTRA_COMMANDS="init"
EXTRA_HELP="   init  Initializes all the OpenWRT stuff"

# Include Mesh work-file
. /usr/share/mesh/mesh.common

#Load config
. /etc/mesh.config

start() {
  build_mesh
}

stop() {
  destroy_mesh
}

init() {
  openwrt_postinst 

}
